version: 0.0
os: linux
files:
  - source: /
    destination: /home/stagpublic1.prestigelabsaffs/public_html
    overwrite: true

permissions:
  - object: /home/stagpublic1.prestigelabsaffs/public_html
    pattern: "**"
    owner: apache
    group: apache
    mode: 775
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    
  AfterInstall:

  ApplicationStop:
